### ISSUE TITLE
[Improvement] Missing english translation of Android-Tips

### ISSUE THREAD

**Issue by ghost** [tangqi92/Android-Tips#22]
Hi, I'm very interesting in what you had written by far, but I don't understand your native language. Is it possible to translate it part after part in English?

**Comment by tangqi92** [comment]
Because this list is just a collection of many tips（And most of it is Chinese）, so I may not be able to solve the problem of translation. Finally, thank you for your support!

**Comment by ghost** [comment]
Well, you made a collection of tips, but you think you can't translate. I think, that's not a problem, a problem might be it's pretty huge collection and you may spend a lot of time translating.

Translation will bring you new visitors, contributors and I'm sure this project will rise fastly...

Ok, I close this issue as "UNRESOLVED".
