### ISSUE TITLE
一些连接已失效

### ISSUE THREAD

**Issue by Diffey** [tangqi92/Android-Tips#8]

**Comment by tangqi92** [comment]
@Runpop 所有的链接我都在编辑时确定正常有效的，对于你所谓的链接失效，你可以「翻墙」后再尝试，如果还是不行，请告知我，我会及时进行修改，再次感谢你对本项目的支持！

**Comment by troyliu0105** [comment]
建议把失效或者需要翻墙的网页内容写在repo里面。

**Comment by tangqi92** [comment]
@troyliu0105 同时还在跟新另一个项目，如果你有时间，我会非常感激。
